#+POSTID: 120
#+DATE: [2011-04-26 Tue 19:40]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY: Informal
#+TAGS: no facebook, no gtalk, irc, old way
#+DESCRIPTION: 
#+TITLE: Getting away from the World
Last [[http://www.pragyan.org/11/][Pragyan]] [fn:pragyan], I decided to quite Facebook. I did it for multiple reasons. Not only it was getting
cluttered by unnecessary and time wasting content, the whole idea of, to quote, ``social networking" seems useless to me.
Still, people ask me if I am on Facebook, and give me that wtf-you-just-said look when I tell them that I am not a user of Facebook.
One more reason that I often find might be one of the major cause of quitting Facebook is its users. The concept of
Facebook is not as bad as how its users use it. Two random guys would be talking all their personal life on their wall, and bloody I'll
get their update on my News Feed. That's so irritating[fn:turnoff]. Privacy is definitely another reason. With Google, I never felt so insecure.
Although I'm still not sure if Google is that private, but with the apparent look-n-feel of the interface, how all my information is provided
under a dash board, how simple it is to delete a Google Account etc., I think it is justifiable to trust Google. Facebook on the other hand
acts like a bitch. Seriously, when I wanted to delete my profile, I came to find out that I can't ! There is no option of deleting your information
on Facebook. You can just `deactivate' your profile. That's insane on the face of it. Moreover, it is rude. Similar (but not same as) to a situation
wherein I give my profile for a matrimonial service, and they refuse to stop advertising me even when I am successfully married (I can't say on a cent percent basis
if Facebook will still advertise me, but them not deleting my profile data do point out to this possibility). When you deactivate your profile,
all your data is still with Facebook, nothing changes, you can re-join Facebook after an year (or longer) with same data, profile, friends etc. It's like your
computer refusing to delete a file, but just making it inaccessible only to you (do note, that Facebook still have all the information with it). Can someone
probably give one good reason to justify this behavior? That is, refusing me to delete my profile. If you ever tried deactivating your profile,
it would ask you all sought of lame reasons why you want to do so. Them, not letting me delete my profile, gives out a feeling that something fishy
is going on.

Yesterday, I decided to stop using GTalk for my chatting needs. Although, I don't have any sound reason of doing so, I can still justify why I did so.
Wasting time? No. I think I can't say I simply wasted time on Gtalk. I used to chat with friends and family and by no means I can classify that under ``wasting time".
I think a more appropriate explanation could be that due to Gtalk, I was spending less time on (my <3) IRC. I must agree that in every way, IRC is much superior way
to chat online. Not only you can go in the respective channel of your taste, personal chatting is also simplified. Not all of my friends
would agree on this thought though, they feel that Gtalk interface is much more user-friendly and (what they incorrectly term it as) intuitive and simple.
IRC provide much finer control about how you should chat. You meet new people on popular networks like =irc.freenode.net=. You tend to discuss
more productive stuff on IRC, than you do on some other add-a-friend like protocol like Jabber (the underlying protocol which Gtalk supports).
I remember the days when I was in twelfth standard and also in my first year of college, I used to be on IRC nearly all the time. I used to discuss stuff on
=##physics=, =#avr=, =##programming= etc. One complain from I used to receive is that IRC requires a client to be downloaded.
I don't understand how is this a problem? There are tons of free IRC clients for both Linux, Windows or any other platform possible. There is even
a [[http://webchat.freenode.net][web client]] for freenode (although I must agree that it is not that neat compared to the web client of Gtalk).

So I got back to IRC on all those channels I used to be. That includes =##sid-avr= which is just a channel in which I am always there. I met my old friend Mathias after
a long time. We started catching up, discussing about how out of touch we both have become to actual coding, writing posts on forums, and helping others. We decided
that we will start posting again, brushing up our C++ and C to the level where it was about an year ago.

I feel good about the fact that I am again back to how I was. As someone correctly pointed out I am leaving everything which makes up this generation of slackers.
I was not a slacker, neither do I want one to be. I won't miss anything or anyone on Facebook or Gtalk. For one reason, that I am not gone out of the world, I am still
contactable. It is just that the means of contacting me is a little different. I prefer it this way. Some of them will say that I want others to do an extra effort to contact me,
I'll rather choose to point out the fact that it is my way of being on the Internet. I have much more experience of being on the Internet than most of my other friends do,
and thus I can confidently say that this life is better. 

[fn:pragyan] Pragyan is the techo-management fest of my institute. I have attended last two years of Pragyan and have both participated and organized events for it.

[fn:turnoff] A Facebook zealot would argue that I can change my =XYZ= setting to properly filtering out what feeds should I be receiving. Observe that then, you
just lose the point of a feed itself. Why I am his/her friend on Facebook if I am not getting his/her update? I'm pretty sure Facebook doesn't have a filter which says
``block annoying feeds' (or does it?). 
