#+POSTID: 62
#+DATE: [2011-04-04 Mon 22:13]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil 
#+CATEGORY: Informal, 
#+TAGS: coffee,mug
#+DESCRIPTION: 
#+TITLE: Why Coffee Mug is important?
Coffee is one important aspect of my life. I can have it in un-metered quantity.
Although, I like having coffee without added milk (/black/ coffee), I usually
don't have it regularly because of the advice given by my father.
I don't have a coffee maker or a coffee filter. Hence, I can only prepare instant
coffee in my room. After experimenting with different method to make coffee,
I found this short simple recipe with which I can make coffee in less than 5 minutes.
#+BEGIN_QUOTE
 - Take 4 table spoon Lukewarm water
 - Add one table spoon milk powder
 - Stir it to dissolve any lumps
 - Add one tsp of sugar and 2 tsp of instant coffee
 - Stir until it mixes well
 - Add boiling water and enjoy the coffee
#+END_QUOTE 

One thing which amplifies and accelerates the experience of coffee drinking
is a coffee mug. If you love coffee, you know what I am talking about.
I have experienced the pale coffee without the mug during the last three months.
It was a Saturday morning, if I remember correctly, I woke up from my bed and found
that my coffee mug was broken into four large pieces. After having my breakfast,
I almost forgot about the incident. After all, how hard can it be to live without a
coffee mug.
I really didn't observe any difference explicitly. But looking back now, I can say 
that the amount of coffee I used prepare and have daily, dropped drastically to zero.
Rather than having coffee in my room, I would run to the nearby coffee stall and have
that ill-configured coffee. 

Just few days back (three days to be exact), I bought a new coffee mug. It is a simple
coffee mug of forest green color, with the word _Coffee_ written in Times New Roman font.

Perfect. The next day itself, I prepared the coffee. I felt so different while preparing 
and having the coffee. Not only, mixing the ingredients are easier (and you don't need
a separate spoon), you can have more coffee at a time than you would have it in a normal glass cup.
You enjoy the coffee something like a superior class (and it certainly takes you to a different level).
It also feels so much better on your hand to hold a mug rather than a stupid glass cup.
I should also mention that cleaning a mug is much easier than cleaning a glass cup (in the worst case
you can just rinse it thoroughly with hot water).

So, if you are a coffee fan and you enjoy preparing coffee for yourself, it is 
a strong recommendation from my side to try out the coffee mug (if you haven't done that already).

Note: I think even tea might taste and feel wonderful if you use a +tea+ mug.

#+/home/siddhant3s/.gnome2/cheese/media/2011-04-04-221517.jpg http://siddhant3s.heliohost.org/wp/wp-content/uploads/2011/04/wpid-2011-04-04-2215172.jpg

#+/home/siddhant3s/.gnome2/cheese/media/coffee_mug.jpg http://siddhant3s.heliohost.org/wp/wp-content/uploads/2011/04/wpid-coffee_mug.jpg
#+//home/siddhant3s/.gnome2/cheese/media/coffee_mug.jpg http://siddhant3s.heliohost.org/wp/wp-content/uploads/2011/04/wpid-coffee_mug1.jpg
#+/home/siddhant3s/.gnome/cheese/media/coffee_mug.jpg http://siddhant3s.heliohost.org/wp/wp-content/uploads/2011/04/wpid-coffee_mug2.jpg

#+///home/siddhant3s/.gnome/cheese/media/coffee\_mug.jpg http://siddhant3s.heliohost.org/wp/wp-content/uploads/2011/04/wpid-coffee_mug3.jpg

#+//home/siddhant3s/.gnome/cheese/media/mug.jpg http://siddhant3s.heliohost.org/wp/wp-content/uploads/2011/04/wpid-mug.jpg
#+/home/siddhant3s/.gnome/cheese/media/mug.jpg http://siddhant3s.heliohost.org/wp/wp-content/uploads/2011/04/wpid-mug1.jpg
